version: "3.8"
services:
  next:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run dev
    container_name: nextjs
    volumes:
      - .:/src/app
      - /src/app/node_modules
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development


