[[redirects]]
  from = "/*"
  to = "https://digitalsitenotice.camden.gov.uk/:splat"
  status = 301
  force = true

[build]
  command = "mkdir .next && cp index.html .next && cp -rp assets .next"


[build.environment]
NETLIFY_NEXT_PLUGIN_SKIP = "true"